// <auto-generated />
namespace BF.AbewoAdressBook.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddCompanyStringtoEntityPerson : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCompanyStringtoEntityPerson));
        
        string IMigrationMetadata.Id
        {
            get { return "201302181537556_Add Company String to Entity Person"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
